In [1]:
from rcm.cot import *

In [2]:
tickers

,direction,metric,assettype,tradertype,activity,cot product,cot source,cot report,regulation,description
ticker,,,,,,,,,,
AACTDXTZ Index,Long,Contracts,NaN,Investment Firms or Credit Institutions,Risk Reducing,Aluminum Alloy Future,London Metal Exchange,MiFID,MiFID,Alu Alloy LME COT Investment/Credit Firm Long ...
AACTXWQO Index,Short,Contracts,NaN,Investment Firms or Credit Institutions,Risk Reducing,Aluminum Alloy Future,London Metal Exchange,MiFID,MiFID,Alu Alloy LME COT Investment/Credit Firm Short...
AACTFFWD Index,Long,Contracts,NaN,Investment Funds,Risk Reducing,Aluminum Alloy Future,London Metal Exchange,MiFID,MiFID,Alu Alloy LME COT Investment Funds Long Contra...
AACTTTSU Index,Short,Contracts,NaN,Investment Funds,Risk Reducing,Aluminum Alloy Future,London Metal Exchange,MiFID,MiFID,Alu Alloy LME COT Investment Funds Short Contr...
AACTHKGO Index,Long,Contracts,NaN,Other Financial Institutions,Risk Reducing,Aluminum Alloy Future,London Metal Exchange,MiFID,MiFID,Alu Alloy LME COT Other Financial Firm Long Co...
...,...,...,...,...,...,...,...,...,...,...
ZSCTXSKZ Index,Short,PercentOI,NaN,Other Financial Institutions,Total,Zinc USD/MT Future,London Metal Exchange,MiFID,MiFID,Zinc LME COT Other Financial Firm Short Pct of...
ZSCTBTTU Index,Long,PercentOI,NaN,Commercial Undertakings,Total,Zinc USD/MT Future,London Metal Exchange,MiFID,MiFID,Zinc LME COT Commercial Undertakings Long Pct ...
ZSCTBNCI Index,Short,PercentOI,NaN,Commercial Undertakings,Total,Zinc USD/MT Future,London Metal Exchange,MiFID,MiFID,Zinc LME COT Commercial Undertakings Short Pct...
ZSCTZLIW Index,Long,PercentOI,NaN,Directive Compliance Obligations,Total,Zinc USD/MT Future,London Metal Exchange,MiFID,MiFID,Zinc LME COT Directive 2003/87/EC Long Pct of ...
ZSCTYOQM Index,Short,PercentOI,NaN,Directive Compliance Obligations,Total,Zinc USD/MT Future,London Metal Exchange,MiFID,MiFID,Zinc LME COT Directive 2003/87/EC Short Pct of...

In [3]:
df

            px_last
date
2006-06-13   105155
2006-06-20   100497
2006-06-27   107394
2006-07-04   118948
2006-07-11   127367
...             ...
2021-07-27   353278
2021-08-03   337498
2021-08-10   325266
2021-08-17   321982
2021-08-24   318887

[794 rows x 1 columns]

In [5]:
tickers.iloc[1:5, [1]]

                   metric
ticker
AACTXWQO Index  Contracts
AACTFFWD Index  Contracts
AACTTTSU Index  Contracts
AACTHKGO Index  Contracts

In [19]:
df2 = tickers.loc[['AACTHKGO Index', 'CFFDQMML Index', 'ZSCTXSKZ Index', 'ZSCTBTTU Index'], ['metric', 'description']]
df2

                   metric                                        description
ticker
AACTHKGO Index  Contracts  Alu Alloy LME COT Other Financial Firm Long Co...
CFFDQMML Index  Contracts  CFTC NYMEX Crude Oil Managed Money Long Contra...
ZSCTXSKZ Index  PercentOI  Zinc LME COT Other Financial Firm Short Pct of...
ZSCTBTTU Index  PercentOI  Zinc LME COT Commercial Undertakings Long Pct ...

In [11]:
df2.to_dict('records')

[{'metric': 'Contracts',
  'description': 'Alu Alloy LME COT Other Financial Firm Long Contracts Risk Reduct'},
 {'metric': 'PercentOI',
  'description': 'Zinc LME COT Other Financial Firm Short Pct of Open Interest Total'},
 {'metric': 'PercentOI',
  'description': 'Zinc LME COT Commercial Undertakings Long Pct of Open Interest Total'}]

In [13]:
print(df2.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>metric</th>
      <th>description</th>
    </tr>
    <tr>
      <th>ticker</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>AACTHKGO Index</th>
      <td>Contracts</td>
      <td>Alu Alloy LME COT Other Financial Firm Long Contracts Risk Reduct</td>
    </tr>
    <tr>
      <th>ZSCTXSKZ Index</th>
      <td>PercentOI</td>
      <td>Zinc LME COT Other Financial Firm Short Pct of Open Interest Total</td>
    </tr>
    <tr>
      <th>ZSCTBTTU Index</th>
      <td>PercentOI</td>
      <td>Zinc LME COT Commercial Undertakings Long Pct of Open Interest Total</td>
    </tr>
  </tbody>
</table>

In [45]:
df2

                   metric                                        description
ticker
AACTHKGO Index          X  Alu Alloy LME COT Other Financial Firm Long Co...
ZSCTXSKZ Index          X  Zinc LME COT Other Financial Firm Short Pct of...
ZSCTBTTU Index  PercentOI  Zinc LME COT Commercial Undertakings Long Pct ...